"""
End-to-end pipeline test: stages 1 to 3 are run on a synthetic recording whose
ground truth is **known**.

This is the most valuable test of the whole suite - it validates the correctness
of all three stages at once: the recording is generated by
:func:`simulate_recording`, the source position, the speed and the excitation time
of every wavefront are prescribed, and the fit has to recover them.

A short recording (3000 ms) is used to keep the test fast.
"""

from __future__ import annotations

import numpy as np
import pytest

from wave_hough_detect import (
    build_result_array,
    detect_all_channels,
    fit_circular,
    fit_linear,
    hough_plane,
    load_recording,
    plane_points,
    simulate_recording,
    spikes_to_table,
)

#: Ground truth of the synthetic recording. 3 seconds and 4 wavefronts: enough to check the numbers and still fast.
TRUTH = dict(source_x0=-3.7, source_y0=-50.0, speed=0.45,
             duration_ms=3000.0, first_wave_ms=500.0, beat_interval_ms=800.0)


@pytest.fixture(scope="module")
def recording(tmp_path_factory):
    """Generate the synthetic recording once; every test in the module shares it."""
    path = tmp_path_factory.mktemp("rec") / "rec.csv"
    _, info = simulate_recording(path, **TRUTH)
    return path, info


@pytest.fixture(scope="module")
def pipeline(recording):
    """Run the whole pipeline and return the intermediate results."""
    path, info = recording
    rec = load_recording(path)
    spike_times, _ = detect_all_channels(rec)
    sp = spikes_to_table(spike_times, rec.channels)
    pts = sp[["x", "y", "t"]].to_numpy(dtype=float)

    res = hough_plane(pts, vote_threshold=8, max_iter=200000,
                      min_detectors=40, seed=1)

    order = np.argsort(sp["t"].to_numpy(), kind="stable")
    arr = build_result_array(sp["x"].to_numpy()[order],
                             sp["y"].to_numpy()[order],
                             sp["t"].to_numpy()[order],
                             res.plane_indices[order], res.n_planes)

    fits = []
    for k in range(1, res.n_planes + 1):
        p = plane_points(arr, k)
        fits.append((k, fit_circular(p), fit_linear(p)))
    fits.sort(key=lambda f: f[1].t0)

    return dict(info=info, rec=rec, spike_times=spike_times, sp=sp, res=res,
                arr=arr, fits=fits)


# --- stage 1 ---
def test_stage1_finds_one_spike_per_wavefront_per_electrode(pipeline):
    """Exactly one spike per wavefront per electrode - the total number of detections equals the number of electrodes times the number of wavefronts."""
    info = pipeline["info"]
    counts = np.array([s.size for s in pipeline["spike_times"]])
    n_waves = len(info["wave_times_ms"])
    assert (counts == n_waves).all(), f"detections per channel {np.unique(counts)}"
    assert counts.sum() == info["n_channels"] * n_waves


def test_stage1_detected_times_match_the_true_arrival_times(pipeline):
    """
    Harder than "the counts match": the detected times must agree with the
    analytic arrival time t = t_wave + distance/v.

    The tolerance is 0.5 ms (about 5 samples) rather than 0.1 ms, for two reasons:
      · a spike position can only be read off at a sample point, which is a
        quantisation of 0.1 ms in itself;
      · the recording contains 0.02 mV of white noise and a 0.5 mV sinusoidal
        baseline, which shift the peak position a little in either direction.
    The measured maximum deviation is about 0.21 ms and the mean deviation is an
    order of magnitude smaller; the two assertions below pin down exactly those
    two quantities.
    """
    info = pipeline["info"]
    sp = pipeline["sp"]
    x0, y0, v = info["source_x0"], info["source_y0"], info["speed"]
    # align wavefront by wavefront: after sorting by t, groups of 64 points
    t_sorted = sp["t"].to_numpy() * 200.0          # back to ms
    xs = sp["x"].to_numpy(); ys = sp["y"].to_numpy()
    dist = np.hypot(xs - x0, ys - y0)

    worst, all_dev = 0.0, []
    for i, tw in enumerate(sorted(info["wave_times_ms"])):
        lo, hi = i * 64, (i + 1) * 64
        expect = tw + dist[lo:hi] / v
        dev = np.abs(t_sorted[lo:hi] - expect)
        all_dev.append(dev)
        worst = max(worst, float(dev.max()))
        assert dev.max() < 0.5, f"wavefront {i + 1} does not line up (maximum deviation {dev.max():.3f} ms)"

    assert worst < 0.5
    assert np.concatenate(all_dev).mean() < 0.15


# --- stage 2 ---
def test_stage2_finds_one_plane_per_wavefront(pipeline):
    info = pipeline["info"]
    assert pipeline["res"].n_planes == len(info["wave_times_ms"])


def test_stage2_every_spike_is_classified(pipeline):
    """On noiseless synthetic data every spike should land in some plane."""
    res = pipeline["res"]
    n = len(pipeline["sp"])
    assert int(res.prediction.sum()) == n


def test_stage2_each_plane_covers_all_electrodes(pipeline):
    res = pipeline["res"]
    sizes = [int((res.plane_indices == k).sum()) for k in range(1, res.n_planes + 1)]
    assert sizes == [64] * res.n_planes


# --- stage 3: comparison with the ground truth ---
def test_stage3_recovers_the_source_position(pipeline):
    info = pipeline["info"]
    x0 = np.array([c.x0 for _, c, _ in pipeline["fits"]])
    y0 = np.array([c.y0 for _, c, _ in pipeline["fits"]])
    assert np.abs(x0 - info["source_x0"]).max() < 0.5
    assert np.abs(y0 - info["source_y0"]).max() < 0.5


def test_stage3_recovers_the_propagation_speed(pipeline):
    info = pipeline["info"]
    v = np.array([c.v for _, c, _ in pipeline["fits"]])
    assert np.abs(v - info["speed"]).max() < 0.01, f"per-plane speeds {np.round(v, 4)}"


def test_stage3_recovers_the_excitation_times(pipeline):
    """
    The fitted t0 must be the prescribed excitation time of the source.
    Note that stage 3 contains an internal scale switch of x200; missing that step
    makes this off by a factor of 200.
    """
    info = pipeline["info"]
    truth = np.sort(np.asarray(info["wave_times_ms"]))
    t0 = np.array([c.t0 for _, c, _ in pipeline["fits"]])
    assert t0.size == truth.size
    assert np.abs(t0 - truth).max() < 2.0, f"fitted {np.round(t0, 1)} vs truth {truth}"


def test_stage3_fit_quality_is_high(pipeline):
    """On noiseless synthetic data R2 should be very close to 1."""
    assert min(c.r2 for _, c, _ in pipeline["fits"]) > 0.99
    assert min(l.r2 for _, _, l in pipeline["fits"]) > 0.98


def test_stage3_linear_model_recovers_direction(pipeline):
    """
    The relation between the coefficients a_tilde, b_tilde of the linear model and
    the true direction: the wavefront normal is proportional to (a_tilde,
    b_tilde). For a far-field wavefront from a source at (-3.7, -50) the direction
    should be essentially along y, so b_tilde is far larger than |a_tilde|.
    """
    for _, c, l in pipeline["fits"]:
        assert abs(l.b) > abs(l.a)
        assert l.b > 0        # the wave comes from the smaller y side
